service: minecraft-serverless-graphql
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  profile: minecraftServerless
functions:
  graphql:
    handler: app/handler.commandCenter
    events:
      - http:
          path: mineql
          method: post
          cors: true
      - http:
          path: mineql
          method: get
          cors: true
plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-parcel
  - serverless-offline
